# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
{
  imports =
    [ 
      (modulesPath + "/installer/scan/not-detected.nix")

      # Import nixos impermanence  module
      "${impermanence}/nixos.nix"
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

 # File system
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/31ee403f-abda-4723-a659-f12edcdc0b72";
      fsType = "xfs";
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/56e21e9e-8aa7-4fad-b7f5-b7aba86961f6";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A00C-2506";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/90ec4a85-5f4a-4480-8182-1eb1896e93ce"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  # networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
