# Default config
layer=top

# Colors
[low]
background={color0.strip}ff
title-color={color7.strip}ff
summary-color={color5.strip}ff
body-color=888888ff

[normal]
background={color0.strip}ff
title-color={color1.strip}ff
summary-color={color5.strip}ff
body-color=888888ff

[critical]
background={color0.strip}ff
title-color={color6.strip}ff
summary-color={color5.strip}ff
body-color=888888ff
