# Default config
layer=top
progress-bar-height=10
title-font="Noto Sans"
body-font="Noto Sans"
summary-font="Noto Sans"

# Timeouts
default-timeout=10
# idle-timeout=0


# Colors
[low]
background={color0.strip}ff
title-color={color7.strip}ff
summary-color={color5.strip}ff
body-color=888888ff

[normal]
background={color0.strip}ff
title-color={color1.strip}ff
summary-color={color5.strip}ff
body-color=888888ff

[critical]
background={color0.strip}ff
title-color={color6.strip}ff
summary-color={color5.strip}ff
body-color=888888ff
